const koa=require('koa')
const app=new koa()
const helmet=require('koa-helmet')
const router=require('./routes/routes')
const statics=require('koa-static')
const path=require('path')
console.log("=====启动成功")
app.use(helmet())
console.log(__dirname)
app.use(statics(path.join(__dirname,'../public')))
app.use(router())
app.listen(8000)
